### ISSUE TITLE
How to get "Other" cell subtype?

### ISSUE THREAD

**Issue by chesnov** [sbooeshaghi/mx#9]
For the cells whose subtype can't be confidently assigned, Supplementary figure 2 of the [Algorithms for a Commons Cell Atlas](https://www.biorxiv.org/content/10.1101/2024.03.23.586413v1.full) paper shows that this pipeline can return "Other" cell label. The notebooks corresponding to figure generation in the paper (e.g. [this one](https://github.com/pachterlab/BGP_2024/blob/main/notebooks/clean_analysis_other.ipynb)) reference a local markers.txt file, which didn't get pushed to github, it seems. None of the markers files currently in the Human repo have "Other" category in their markers.txt. All the code mentioning "other" in the mx assign is currently commented out. 

Therefore, how can I get the pipeline to output "Other" cell subtype during assignment? Is it correct to define "Other" cell subtype with a list of housekeeping genes like GAPDH which would show up everywhere?

**Comment by sbooeshaghi** [comment]
Hi @chesnov, there are a few ways to define "other". The way we have done it is to simply add a cell type to the markers.txt with no marker genes:

```txt
ctA    g1,g2
ctB    g2,g4
ctC   g1,g3
other
```

The other way, as you pointed out, is to simply pick broadly expressed genes that are not markers for your other cell types.

**Comment by chesnov** [comment]
Awesome, thank you!
